-- 여기까지 실행 후 왼쪽 접속 탭에서 + 버튼으로 계정 추가

DROP TABLE MESSAGE;
DROP TABLE CHATROOM;
DROP TABLE REVIEW;
DROP TABLE TB_LIKE;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE TB_OPTION;
DROP TABLE TEMP_OPTION;
DROP TABLE FOLLOW;
DROP TABLE SEARCH_LOG;
DROP TABLE QNA;
DROP TABLE NOTICE;
DROP TABLE AUTH;
DROP TABLE TEMPORARY;
DROP TABLE PRODUCT;
DROP TABLE SELLER_PROFILE;
DROP TABLE SELLER_APPLICATION;
DROP TABLE TB_USER;
--


DROP SEQUENCE SEQ_TB_USER_NO;
DROP SEQUENCE SEQ_SELLER_PROFILE_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_TEMP_NO;
DROP SEQUENCE SEQ_ORDER_NO;
DROP SEQUENCE SEQ_OPTION_NO;
DROP SEQUENCE SEQ_TEMP_OPTION_NO;
DROP SEQUENCE SEQ_REVIEW_NO;
DROP SEQUENCE SEQ_FOLLOW_NO;
DROP SEQUENCE SEQ_SEARCH_LOG_ID;
DROP SEQUENCE SEQ_CHATROOM_NO;
DROP SEQUENCE SEQ_MSG_NO;
DROP SEQUENCE SEQ_QNA_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
--
DROP SEQUENCE SEQ_SELLER_APP_NO


-- 회원 테이블
CREATE TABLE TB_USER (
    USER_NO NUMBER CONSTRAINT U_PK PRIMARY KEY,
    USER_ID VARCHAR2(20) CONSTRAINT U_ID_NN NOT NULL
                         CONSTRAINT U_ID_UQ UNIQUE,
    USER_PWD VARCHAR2(100) CONSTRAINT U_PWD_NN NOT NULL,
    USER_NAME VARCHAR2(20) CONSTRAINT U_NAME_NN NOT NULL,
    NICKNAME VARCHAR2(24) CONSTRAINT NICK_NN NOT NULL
                          CONSTRAINT NICK_UQ UNIQUE,
    BIRTH_DATE DATE CONSTRAINT BD_NN NOT NULL,
    GENDER VARCHAR2(1) CONSTRAINT GEN_CHK CHECK(GENDER IN ('M', 'F'))
                       CONSTRAINT GEN_NN NOT NULL,
    EMAIL VARCHAR2(50) CONSTRAINT EMAIL_NN NOT NULL,
    PHONE VARCHAR2(13) CONSTRAINT PHONE_NN NOT NULL,
    ORIGIN_PROFILE VARCHAR2(100),
    MODIFY_PROFILE VARCHAR2(100),
    POSTCODE VARCHAR2(10) CONSTRAINT PCODE_NN NOT NULL,
    MAIN_ADDRESS VARCHAR2(100) CONSTRAINT MA_NN NOT NULL,
    DETAIL_ADDRESS VARCHAR2(200) CONSTRAINT DA_NN NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE CONSTRAINT EDATE_NN NOT NULL,
    USER_YN VARCHAR2(1) DEFAULT 'N' CONSTRAINT U_YN_CHK CHECK(USER_YN IN ('Y', 'N'))
                                        CONSTRAINT U_YN_NN NOT NULL,
    USER_ROLE VARCHAR2(6) CONSTRAINT U_ROLE_CHK CHECK (USER_ROLE IN ('USER', 'SELLER', 'ADMIN', 'MAKER', 'SUPPORTER'))
                          CONSTRAINT U_ROLE_NN NOT NULL
);


-- 판매자 프로필 테이블
CREATE TABLE SELLER_PROFILE (
    SELLER_NO NUMBER CONSTRAINT SEL_PK PRIMARY KEY,
    INTRODUCTION VARCHAR2(1000),
    USER_NO NUMBER CONSTRAINT SEL_UNO_NN NOT NULL,
    CONSTRAINT SP_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 판매자 전환 신청 테이블
CREATE TABLE SELLER_APPLICATION (
    APPLICATION_NO NUMBER CONSTRAINT SEL_APP_PK PRIMARY KEY,
    USER_NO NUMBER CONSTRAINT SEL_APP_UNO_NN NOT NULL,
    APPLICANT_NAME VARCHAR2(100) CONSTRAINT SEL_APP_NAME_NN NOT NULL,
    APPLICANT_EMAIL VARCHAR2(200) CONSTRAINT SEL_APP_EMAIL_NN NOT NULL,
    APPLICANT_PHONE VARCHAR2(30) CONSTRAINT SEL_APP_PHONE_NN NOT NULL,
    BUSINESS_NAME VARCHAR2(200) CONSTRAINT SEL_APP_BNAME_NN NOT NULL,
    BUSINESS_NUMBER VARCHAR2(50),
    WEBSITE VARCHAR2(300),
    BRAND_DESCRIPTION VARCHAR2(2000),
    DOCUMENT_PATH VARCHAR2(500),
    STATUS VARCHAR2(10) DEFAULT 'PENDING' CONSTRAINT SEL_APP_STATUS_CHK CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED'))
                                            CONSTRAINT SEL_APP_STATUS_NN NOT NULL,
    ADMIN_MEMO VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE CONSTRAINT SEL_APP_CREATED_NN NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE CONSTRAINT SEL_APP_UPDATED_NN NOT NULL,
    CONSTRAINT SEL_APP_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 제품 테이블

CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER CONSTRAINT PRO_PK PRIMARY KEY,
    PRODUCT_TITLE VARCHAR2(100) CONSTRAINT PRO_TI_NN NOT NULL,
    PRODUCT_DESC VARCHAR2(2000) CONSTRAINT PRO_DES_NN NOT NULL,
    STORY_HTML CLOB,
    STORY_JSON CLOB,
    TARGET_AMOUNT NUMBER CONSTRAINT PRO_TAMOUNT_NN NOT NULL,
    CURRENT_AMOUNT NUMBER CONSTRAINT PRO_CAMOUNT_NN NOT NULL,
    FUND_START_DATE DATE CONSTRAINT PRO_FSDATE_NN NOT NULL,
    FUND_END_DATE DATE CONSTRAINT PRO_FEDATE_NN NOT NULL,
     SHIP_START_DATE DATE CONSTRAINT PRO_SDATE_NN NOT NULL,
    PRODUCT_STATUS VARCHAR2(7) DEFAULT 'OPEN'
        CONSTRAINT PRO_STATUS_CHK CHECK (PRODUCT_STATUS IN ('OPEN','CLOSE','SUCCESS','FAIL'))
        CONSTRAINT PRO_STATUS_NN NOT NULL,
    CATEGORY VARCHAR2(30) CONSTRAINT PRO_CATE_NN NOT NULL,
    ORIGIN_THUMBNAIL VARCHAR2(100) CONSTRAINT PRO_OTHUMB_NN NOT NULL,
    MODIFY_THUMBNAIL VARCHAR2(100),
    REJECT_REASON VARCHAR2(1000),
    CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT PRO_CDATE_NN NOT NULL,
    PRODUCT_YN VARCHAR2(1) DEFAULT 'N',
    SELLER_NO NUMBER CONSTRAINT PRO_SNO_NN NOT NULL,
    CONSTRAINT PRO_SNO_FK FOREIGN KEY (SELLER_NO)
        REFERENCES SELLER_PROFILE(SELLER_NO)
);




-- 임시저장 테이블
CREATE TABLE TEMPORARY (
    TEMP_NO NUMBER CONSTRAINT TEMP_PK PRIMARY KEY,
    TEMP_TITLE VARCHAR2(100),
    TEMP_DESC VARCHAR2(2000),
    TARGET_AMOUNT NUMBER,
    FUND_START_DATE DATE,
    FUND_END_DATE DATE,
    CATEGORY VARCHAR2(30),
    ORIGIN_THUMBNAIL VARCHAR2(100),
    TEMP_STORY_HTML CLOB,
    TEMP_STORY_JSON CLOB,
    SHIP_START_DATE DATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    SELLER_NO NUMBER,
    CONSTRAINT TEMP_SNO_FK FOREIGN KEY (SELLER_NO)
        REFERENCES SELLER_PROFILE(SELLER_NO),
    TEMP_STATUS VARCHAR2(1) DEFAULT 'Y'
);

CREATE TABLE TEMPORARY (
    TEMP_NO NUMBER CONSTRAINT TEMP_PK PRIMARY KEY,
    TEMP_TITLE VARCHAR2(100),
    TEMP_DESC VARCHAR2(2000),
    TARGET_AMOUNT NUMBER,
    FUND_START_DATE DATE,
    FUND_END_DATE DATE,
    CATEGORY VARCHAR2(30),
    ORIGIN_THUMBNAIL VARCHAR2(100),
    TEMP_STORY_HTML CLOB,
    TEMP_STORY_JSON CLOB,
    SHIP_START_DATE DATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    SELLER_NO NUMBER,
    CONSTRAINT TEMP_SNO_FK FOREIGN KEY (SELLER_NO)
        REFERENCES SELLER_PROFILE(SELLER_NO),
    TEMP_STATUS VARCHAR2(1) DEFAULT 'Y'
);


-- 구매내역 테이블
CREATE TABLE ORDERS (
    ORDER_NO VARCHAR2(200) CONSTRAINT ORD_PK PRIMARY KEY,
    ORDER_AMOUNT NUMBER CONSTRAINT ORD_OAMOUNT_NN NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE CONSTRAINT ORD_ODATE_NN NOT NULL,
    ORDER_STATUS VARCHAR2(7) DEFAULT 'PAY' CONSTRAINT ORD_OSTATUS_CHK CHECK (ORDER_STATUS IN('PAY', 'CANCLE', 'REFUND', 'PENDING'))
                                           CONSTRAINT ORD_OSTATUS_NN NOT NULL,
    DELIVERY_STATUS VARCHAR2(10) DEFAULT 'READY' CONSTRAINT ORD_DSTATUS_CHK CHECK (DELIVERY_STATUS IN('READY', 'SHIPPING', 'DELIVERED'))
                                                 CONSTRAINT ORD_DSTATUS_NN NOT NULL,
    POSTCODE VARCHAR2(5) CONSTRAINT ORD_PCODE_NN NOT NULL,
    ADDRESS VARCHAR2(100) CONSTRAINT ORD_ADD_NN NOT NULL,
    USER_NO NUMBER CONSTRAINT ORD_UNO_NN NOT NULL,
    CONSTRAINT ORD_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 옵션 테이블
CREATE TABLE TB_OPTION (
    OPTION_NO NUMBER CONSTRAINT OPT_PK PRIMARY KEY,
    OPTION_NAME VARCHAR2(100) CONSTRAINT OPT_ONAME_NN NOT NULL,
    OPTION_CONTENT VARCHAR2(1000) CONSTRAINT OPT_CONTENT_NN NOT NULL,
    OPTION_PRICE NUMBER CONSTRAINT OPT_PRICE_NN NOT NULL,
    PRODUCT_NO NUMBER CONSTRAINT OPT_PNO_NN NOT NULL,
    CONSTRAINT OPT_PNO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)
);


-- 옵션 임시저장 테이블
CREATE TABLE TEMP_OPTION (
    OPTION_NO NUMBER CONSTRAINT TEMP_OP_PK PRIMARY KEY,
    OPTION_NAME VARCHAR2(100) ,
    OPTION_CONTENT VARCHAR2(1000),
    OPTION_PRICE NUMBER,
    TEMP_NO NUMBER
);

-- 상세주문 테이블
CREATE TABLE ORDER_DETAIL (
    QUANTITY NUMBER CONSTRAINT OD_QUAN_NN NOT NULL,
    ORDER_NO VARCHAR2(200) CONSTRAINT OD_ORNO_NN NOT NULL,
    OPTION_NO NUMBER CONSTRAINT OD_OPNO_NN NOT NULL,
    CONSTRAINT OD_ORNO_FK FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    CONSTRAINT OD_OPNO_FK FOREIGN KEY (OPTION_NO) REFERENCES TB_OPTION(OPTION_NO)
);


-- 후기 테이블
CREATE TABLE REVIEW (
    REVIEW_NO NUMBER CONSTRAINT REV_PK PRIMARY KEY,
    REVIEW_TITLE VARCHAR2(300) CONSTRAINT REV_TITLE_NN NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) CONSTRAINT REV_CON_NN NOT NULL,
    REVIEW_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT REV_CDATE_NN NOT NULL,
    RATING NUMBER CONSTRAINT REV_RATING_CHK CHECK (RATING BETWEEN 0 AND 5)
                  CONSTRAINT REV_RATING_NN NOT NULL,
    ORDER_NO VARCHAR2(200) CONSTRAINT REV_ONO_NN NOT NULL,
    USER_NO NUMBER CONSTRAINT REV_UNO_NN NOT NULL,
    CONSTRAINT REV_ONO_FK FOREIGN KEY (ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    CONSTRAINT REV_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 좋아요 테이블
CREATE TABLE TB_LIKE (
    PRODUCT_NO NUMBER CONSTRAINT LIKE_PNO_NN NOT NULL,
    USER_NO NUMBER CONSTRAINT LIKE_UNO_NN NOT NULL,
    CONSTRAINT LIKE_PNO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
    CONSTRAINT LIKE_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 팔로우 테이블
CREATE TABLE FOLLOW (
    FOLLOWING NUMBER CONSTRAINT FLW_FLWING_NN NOT NULL,
    SELLER_NO NUMBER CONSTRAINT FLW_SNO_NN NOT NULL,
    CONSTRAINT FLW_FLWING_FK FOREIGN KEY (FOLLOWING) REFERENCES TB_USER(USER_NO),
    CONSTRAINT FLW_SNO_FK FOREIGN KEY (SELLER_NO) REFERENCES SELLER_PROFILE(SELLER_NO)
);

-- 검색 로그 테이블
CREATE TABLE SEARCH_LOG (
    LOG_ID NUMBER CONSTRAINT SLOG_PK PRIMARY KEY,
    KEYWORD VARCHAR2(100) CONSTRAINT SLOG_KEYWORD_NN NOT NULL,
    SEARCHED_AT DATE DEFAULT SYSDATE CONSTRAINT SLOG_DATE_NN NOT NULL
);

-- 채팅방 테이블
CREATE TABLE CHATROOM (
    CHATROOM_NO NUMBER CONSTRAINT CH_ROOM_PK PRIMARY KEY,
    CHATROOM_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT CH_ROOM_CDATE_NN NOT NULL,
    BUYER NUMBER CONSTRAINT CH_BUY_NN NOT NULL,
    SELLER NUMBER CONSTRAINT CH_SEL_NN NOT NULL,
    CONSTRAINT CH_ROOM_BUY_FK FOREIGN KEY (BUYER) REFERENCES TB_USER(USER_NO),
    CONSTRAINT CH_ROOM_SEL_FK FOREIGN KEY (SELLER) REFERENCES TB_USER(USER_NO)
);

-- 채팅 메세지 테이블
CREATE TABLE MESSAGE (
    MSG_NO NUMBER CONSTRAINT MSG_PK PRIMARY KEY,
    MSG_CONTENT VARCHAR2(2000) CONSTRAINT MSG_CON_NN NOT NULL,
    SEND_DATE DATE DEFAULT SYSDATE CONSTRAINT MSG_SDATE_NN NOT NULL,
    READ_YN VARCHAR2(1) DEFAULT 'N' CONSTRAINT MSG_YN_CHK CHECK (READ_YN IN ('Y', 'N'))
                                        CONSTRAINT MSG_YN_NN NOT NULL,
    RECEIVER NUMBER CONSTRAINT MSG_REC_NN NOT NULL,
    SENDER NUMBER CONSTRAINT MSG_SEN_NN NOT NULL,
    CHATROOM_NO NUMBER CONSTRAINT MSG_CHROOM_NN NOT NULL,
    CONSTRAINT MSG_REC_FK FOREIGN KEY (RECEIVER) REFERENCES TB_USER(USER_NO),
    CONSTRAINT MSG_SEN_FK FOREIGN KEY (SENDER) REFERENCES TB_USER(USER_NO),
    CONSTRAINT MSG_CHROOM_FK FOREIGN KEY (CHATROOM_NO) REFERENCES CHATROOM(CHATROOM_NO)
);

-- 문의 게시판
-- MAPPER 단계에서 ANSWER_DATE = SYSDATE로 작성하면 됨. 기본값 X
CREATE TABLE QNA (
    QNA_NO NUMBER CONSTRAINT QNA_PK PRIMARY KEY,
    QNA_TITLE VARCHAR2(200) CONSTRAINT QNA_TITLE_NN NOT NULL,
    QNA_CONTENT VARCHAR2(2000) CONSTRAINT QNA_CON_NN NOT NULL,
    QNA_DATE DATE DEFAULT SYSDATE CONSTRAINT QNA_DATE_NN NOT NULL,
    ANSWER_CONTENT VARCHAR2(2000),
    ANSWER_DATE DATE,
    USER_NO NUMBER CONSTRAINT QNA_UNO_NN NOT NULL,
    CONSTRAINT QNA_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
);

-- 공지사항 게시판
CREATE TABLE NOTICE (
    NOTICE_NO NUMBER CONSTRAINT NOTICE_PK PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(200) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) CONSTRAINT NOTICE_CON_NN NOT NULL,
    NOTICE_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT NOTICE_CDATE_NN NOT NULL,
    NOTICE_VIEW NUMBER DEFAULT 0 CONSTRAINT NOTICE_VIEW_NN NOT NULL,
    NOTICE_YN VARCHAR2(1) DEFAULT 'N' CONSTRAINT NOTICE_YN_CHK CHECK (NOTICE_YN IN ('Y', 'N'))
                                          CONSTRAINT NOTICE_YN_NN NOT NULL
);

-- 인증 테이블
CREATE TABLE AUTH (
    EMAIL VARCHAR2(50) CONSTRAINT AUTH_EMAIL_NN NOT NULL,
    AUTH_CODE NUMBER CONSTRAINT AUTH_CODE_NN NOT NULL,
    AUTH_DATE DATE DEFAULT SYSDATE CONSTRAINT AUTH_DATE_NN NOT NULL
);

  
COMMIT;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_TB_USER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_SELLER_PROFILE_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_SELLER_APP_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_TEMP_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_ORDER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_OPTION_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_TEMP_OPTION_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_FOLLOW_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_SEARCH_LOG_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_CHATROOM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_MSG_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_QNA_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

--

-- 컬럼 설명
COMMENT ON TABLE TB_USER IS '회원 기본 정보 테이블';

COMMENT ON COLUMN TB_USER.USER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN TB_USER.USER_ID IS '아이디';
COMMENT ON COLUMN TB_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN TB_USER.NICKNAME IS '닉네임';
COMMENT ON COLUMN TB_USER.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN TB_USER.GENDER IS '성별(M/F)';
COMMENT ON COLUMN TB_USER.EMAIL IS '이메일';
COMMENT ON COLUMN TB_USER.PHONE IS '전화번호';
COMMENT ON COLUMN TB_USER.ORIGIN_PROFILE IS '프로필사진 원본파일명';
COMMENT ON COLUMN TB_USER.MODIFY_PROFILE IS '프로필사진 수정파일명';
COMMENT ON COLUMN TB_USER.POSTCODE IS '우편번호';
COMMENT ON COLUMN TB_USER.MAIN_ADDRESS IS '기본 주소';
COMMENT ON COLUMN TB_USER.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN TB_USER.USER_YN IS '회원 상태(Y/N)';
COMMENT ON COLUMN TB_USER.USER_ROLE IS '회원 권한(USER/SELLER/ADMIN)';
---------------------------------------------------------------------
COMMENT ON TABLE SELLER_PROFILE IS '판매자 프로필 테이블';

COMMENT ON COLUMN SELLER_PROFILE.SELLER_NO IS '판매자 번호(PK)';
COMMENT ON COLUMN SELLER_PROFILE.INTRODUCTION IS '판매자 소개';
COMMENT ON COLUMN SELLER_PROFILE.USER_NO IS '회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE SELLER_APPLICATION IS '판매자 전환 신청 테이블';

COMMENT ON COLUMN SELLER_APPLICATION.APPLICATION_NO IS '신청 번호(PK)';
COMMENT ON COLUMN SELLER_APPLICATION.USER_NO IS '신청자 회원 번호';
COMMENT ON COLUMN SELLER_APPLICATION.APPLICANT_NAME IS '신청자 이름';
COMMENT ON COLUMN SELLER_APPLICATION.APPLICANT_EMAIL IS '신청자 이메일';
COMMENT ON COLUMN SELLER_APPLICATION.BUSINESS_NAME IS '브랜드/사업명';
COMMENT ON COLUMN SELLER_APPLICATION.STATUS IS '신청 상태(PENDING/APPROVED/REJECTED)';
---------------------------------------------------------------------
COMMENT ON TABLE PRODUCT IS '제품(푸슐랭) 정보 테이블';

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '제품 번호(PK)';
COMMENT ON COLUMN PRODUCT.PRODUCT_TITLE IS '제품 제목';
COMMENT ON COLUMN PRODUCT.PRODUCT_DESC IS '제품 상세 설명';
COMMENT ON COLUMN PRODUCT.TARGET_AMOUNT IS '목표 금액';
COMMENT ON COLUMN PRODUCT.CURRENT_AMOUNT IS '현재 후원 금액';
COMMENT ON COLUMN PRODUCT.FUND_START_DATE IS '펀딩 시작일';
COMMENT ON COLUMN PRODUCT.FUND_END_DATE IS '펀딩 종료일';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '상품 상태(OPEN/CLOSE/SUCCESS/FAIL)';
COMMENT ON COLUMN PRODUCT.CATEGORY IS '카테고리';
COMMENT ON COLUMN PRODUCT.ORIGIN_THUMBNAIL IS '썸네일 원본파일명';
COMMENT ON COLUMN PRODUCT.MODIFY_THUMBNAIL IS '썸네일 수정파일명';
COMMENT ON COLUMN PRODUCT.REJECT_REASON IS '관리자 반려 사유';
COMMENT ON COLUMN PRODUCT.SHIP_START_DATE IS '예상 발송 시작일';
COMMENT ON COLUMN PRODUCT.CREATE_DATE IS '등록일';
COMMENT ON COLUMN PRODUCT.PRODUCT_YN IS '프로젝트 승인 여부(Y/N)';
COMMENT ON COLUMN PRODUCT.SELLER_NO IS '판매자 회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE TEMPORARY IS '임시 저장 테이블';

COMMENT ON COLUMN TEMPORARY.TEMP_NO IS '임시 저장 번호(PK)';
COMMENT ON COLUMN TEMPORARY.TEMP_TITLE IS '임시 제품 제목';
COMMENT ON COLUMN TEMPORARY.TEMP_DESC IS '임시 제품 설명';
COMMENT ON COLUMN TEMPORARY.TARGET_AMOUNT IS '임시 목표 금액';
COMMENT ON COLUMN TEMPORARY.FUND_START_DATE IS '임시 펀딩 시작일';
COMMENT ON COLUMN TEMPORARY.FUND_END_DATE IS '임시 펀딩 종료일';
COMMENT ON COLUMN TEMPORARY.CATEGORY IS '임시 카테고리';
COMMENT ON COLUMN TEMPORARY.ORIGIN_THUMBNAIL IS '썸네일 원본파일명';
COMMENT ON COLUMN TEMPORARY.MODIFY_THUMBNAIL IS '썸네일 수정파일명';
COMMENT ON COLUMN TEMPORARY.SHIP_START_DATE IS '임시 배송시작일';
COMMENT ON COLUMN TEMPORARY.UPDATE_DATE IS '임시 저장 수정일';
COMMENT ON COLUMN TEMPORARY.USER_NO IS '회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE ORDERS IS '구매 내역 테이블';

COMMENT ON COLUMN ORDERS.ORDER_NO IS '주문 번호(PK)';
COMMENT ON COLUMN ORDERS.ORDER_AMOUNT IS '결제 금액';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS '주문 날짜';
COMMENT ON COLUMN ORDERS.ORDER_STATUS IS '주문 상태(PAY/CANCLE/REFUND/PENDING)';
COMMENT ON COLUMN ORDERS.DELIVERY_STATUS IS '배송 상태(READY/SHIPPING/DELIVERED)';
COMMENT ON COLUMN ORDERS.POSTCODE IS '우편번호';
COMMENT ON COLUMN ORDERS.ADDRESS IS '배송 주소';
COMMENT ON COLUMN ORDERS.USER_NO IS '구매자 회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE TB_OPTION IS '프로젝트 제품 옵션 테이블';

COMMENT ON COLUMN TB_OPTION.OPTION_NO IS '옵션 번호';
COMMENT ON COLUMN TB_OPTION.OPTION_NAME IS '옵션명';
COMMENT ON COLUMN TB_OPTION.OPTION_CONTENT IS '옵션 내용';
COMMENT ON COLUMN TB_OPTION.OPTION_PRICE IS '옵션 가격';
COMMENT ON COLUMN TB_OPTION.PRODUCT_NO IS '제품 번호(FK)';

---------------------------------------------------------------------
COMMENT ON TABLE TEMP_OPTION IS '임시저장 제품 옵션 테이블';

COMMENT ON COLUMN TEMP_OPTION.OPTION_NO IS '임시 옵션 번호';
COMMENT ON COLUMN TEMP_OPTION.OPTION_NAME IS '임시 옵션명';
COMMENT ON COLUMN TEMP_OPTION.OPTION_CONTENT IS '임시 옵션 내용';
COMMENT ON COLUMN TEMP_OPTION.OPTION_PRICE IS '임시 옵션 가격';
COMMENT ON COLUMN TEMP_OPTION.PRODUCT_NO IS '임시 제품 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE ORDER_DETAIL IS '상세주문 테이블';

COMMENT ON COLUMN ORDER_DETAIL.QUANTITY IS '수량';
COMMENT ON COLUMN ORDER_DETAIL.ORDER_NO IS '주문 번호(FK)';
COMMENT ON COLUMN ORDER_DETAIL.OPTION_NO IS '옵션 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE REVIEW IS '후기 테이블';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '후기 번호(PK)';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '후기 제목';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '후기 내용';
COMMENT ON COLUMN REVIEW.REVIEW_CREATE_DATE IS '후기 작성일';
COMMENT ON COLUMN REVIEW.RATING IS '별점';
COMMENT ON COLUMN REVIEW.ORDER_NO IS '주문 번호(FK)';
COMMENT ON COLUMN REVIEW.USER_NO IS '회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE TB_LIKE IS '좋아요 테이블';

COMMENT ON COLUMN TB_LIKE.PRODUCT_NO IS '좋아요한 제품 번호(FK)';
COMMENT ON COLUMN TB_LIKE.USER_NO IS '좋아요한 회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE FOLLOW IS '팔로우 테이블';

COMMENT ON COLUMN FOLLOW.SELLER_NO IS '판매자 번호(FK)';
COMMENT ON COLUMN FOLLOW.FOLLOWING IS '팔로잉 회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE SEARCH_LOG IS '검색어 기록 테이블';

COMMENT ON COLUMN SEARCH_LOG.LOG_ID IS '검색 로그 번호(PK)';
COMMENT ON COLUMN SEARCH_LOG.KEYWORD IS '검색어(소문자 저장)';
COMMENT ON COLUMN SEARCH_LOG.SEARCHED_AT IS '검색 시각';
---------------------------------------------------------------------
COMMENT ON TABLE CHATROOM IS '채팅방 테이블';

COMMENT ON COLUMN CHATROOM.CHATROOM_NO IS '채팅방 번호(PK)';
COMMENT ON COLUMN CHATROOM.CHATROOM_CREATE_DATE IS '채팅방 생성일';
COMMENT ON COLUMN CHATROOM.BUYER IS '채팅방 참여 구매자(FK)';
COMMENT ON COLUMN CHATROOM.SELLER IS '채팅방 참여 판매자(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE MESSAGE IS '채팅 메시지 테이블';

COMMENT ON COLUMN MESSAGE.MSG_NO IS '메시지 번호(PK)';
COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '메시지 내용';
COMMENT ON COLUMN MESSAGE.SEND_DATE IS '전송 일시';
COMMENT ON COLUMN MESSAGE.READ_YN IS '읽음 상태(Y/N)';
COMMENT ON COLUMN MESSAGE.RECEIVER IS '수신자 회원 번호(FK)';
COMMENT ON COLUMN MESSAGE.SENDER IS '발신자 회원 번호(FK)';
COMMENT ON COLUMN MESSAGE.CHATROOM_NO IS '채팅방 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE QNA IS '문의/질문 게시판';

COMMENT ON COLUMN QNA.QNA_NO IS 'QnA 번호(PK)';
COMMENT ON COLUMN QNA.QNA_TITLE IS '문의 제목';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '문의 내용';
COMMENT ON COLUMN QNA.QNA_DATE IS '문의 작성일';
COMMENT ON COLUMN QNA.ANSWER_CONTENT IS '답변 내용';
COMMENT ON COLUMN QNA.ANSWER_DATE IS '답변 작성일';
COMMENT ON COLUMN QNA.USER_NO IS '회원 번호(FK)';
---------------------------------------------------------------------
COMMENT ON TABLE NOTICE IS '공지사항 테이블';

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지 번호(PK)';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지 내용';
COMMENT ON COLUMN NOTICE.NOTICE_CREATE_DATE IS '공지 작성일';
COMMENT ON COLUMN NOTICE.NOTICE_VIEW IS '조회수';
COMMENT ON COLUMN NOTICE.NOTICE_YN IS '공지사항 삭제 여부(Y/N)';
---------------------------------------------------------------------
COMMENT ON TABLE AUTH IS '이메일 인증코드 테이블';

COMMENT ON COLUMN AUTH.EMAIL IS '인증 이메일';
COMMENT ON COLUMN AUTH.AUTH_CODE IS '인증 코드';
COMMENT ON COLUMN AUTH.AUTH_DATE IS '인증번호 발급일';


COMMIT;


ALTER TABLE TB_USER MODIFY USER_ROLE VARCHAR2(20 BYTE);
ALTER TABLE TB_USER DROP CONSTRAINT U_ROLE_CHK;
ALTER TABLE TB_USER ADD CONSTRAINT U_ROLE_CHK
CHECK (USER_ROLE IN ('USER', 'SELLER', 'ADMIN', 'MAKER', 'SUPPORTER'));
COMMIT;


-- 1. 기존의 좁은 제약조건 삭제
ALTER TABLE PRODUCT DROP CONSTRAINT PRO_STATUS_CHK;
-- 2. 모든 상태값을 포함하여 다시 생성
ALTER TABLE PRODUCT ADD CONSTRAINT PRO_STATUS_CHK
CHECK (PRODUCT_STATUS IN (
    'WAITING',  -- 심사대기
    'OPEN',     -- 진행중
    'REJECT',   -- 반려
    'CLOSE',    -- 종료
    'SUCCESS',  -- 성공
    'FAIL',     -- 실패
    'STOP',     -- 중단
    'BAN',      -- 제재
    'PREVIEW'   -- 공개예정
));
-- 3. 저장
COMMIT;
-- 1. FAQ 테이블 생성
CREATE TABLE TB_FAQ (
    FAQ_NO NUMBER PRIMARY KEY,
    FAQ_QUESTION VARCHAR2(1000) NOT NULL,
    FAQ_ANSWER VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE
);
-- 2. 시퀀스 생성
CREATE SEQUENCE SEQ_FAQ_NO NOCACHE;
-- 기존 더미 데이터 10개 DB에 넣기
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '펀딩이 성공해야만 음식을 받을 수 있나요?', '네, 그렇습니다. 음식 펀딩은 목표 금액이 100% 이상 달성되어야만 생산 및 배송이 시작됩니다. 만약 목표에 달성하지 못하면 결제된 금액은 전액 환불됩니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '신선식품인데 배송은 안전하게 오나요?', 'Foodding은 음식 전문 펀딩인 만큼 모든 상품을 신선도 유지 전용 박스와 아이스팩을 동봉하여 배송합니다. 상품 특성에 따라 냉장/냉동 차량으로 안전하게 전달해 드립니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '펀딩 결제는 언제 이루어지나요?', '펀딩에 참여한 즉시 결제가 예약되며, 목표 금액이 달성되어 펀딩이 종료된 다음 날 최종적으로 결제가 승인됩니다. 실패 시 예약된 결제는 자동으로 취소됩니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '음식에 문제가 있을 때 교환이나 환불이 가능한가요?', '식품의 특성상 단순 변심에 의한 환불은 어려울 수 있습니다. 다만, 배송 중 파손이나 상품 변질이 확인될 경우 수령 후 24시간 이내에 사진과 함께 마이페이지 > 1:1 문의를 남겨주시면 즉시 처리해 드립니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '도착 날짜를 지정할 수 있나요?', '펀딩 상품은 한꺼번에 대량 생산되는 방식이므로 정확한 배송일 지정은 어렵습니다. 다만, 생산 완료 후 예상 배송 시작일을 공지사항과 알림톡을 통해 미리 안내해 드립니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '알레르기 유발 물질 정보를 어디서 확인하나요?', '각 펀딩 상세 페이지 하단에 ''식품위생법에 의한 표시사항''이 기재되어 있습니다. 특정 원재료에 대한 알레르기가 있으신 분들은 펀딩 전 반드시 확인해 주시기 바랍니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '제주도나 도서산간 지역도 배송이 가능한가요?', '상품 종류(냉동/신선)에 따라 배송 가능 지역이 제한될 수 있습니다. 펀딩 시 ''배송지 선택'' 단계에서 배송 가능 여부를 확인할 수 있으며, 추가 배송비가 발생할 수 있습니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '펀딩한 음식을 맛있게 먹는 법(조리법)을 알 수 있나요?', '메이커(생산자)가 제공하는 최적의 레시피 카드가 상품에 동봉되어 배송됩니다. 또한 상세 페이지 내 ''커뮤니티'' 탭에서 다른 서포터들의 조리 팁도 확인하실 수 있습니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '단체 주문이나 대량 구매가 가능한가요?', '별도의 대량 구매 리워드가 설정되어 있지 않은 경우, 1:1 문의를 통해 메이커에게 수량 조절 가능 여부를 문의해 주시면 안내를 도와드리겠습니다.');
INSERT INTO TB_FAQ (FAQ_NO, FAQ_QUESTION, FAQ_ANSWER) VALUES (SEQ_FAQ_NO.NEXTVAL, '결제 수단을 변경하고 싶어요.', '펀딩이 진행 중인 상태에서는 마이페이지 > 참여한 펀딩 상세 내역에서 결제 수단을 변경하실 수 있습니다. 단, 펀딩 종료 후에는 변경이 어렵습니다.');
COMMIT;
