-- 1. 서비스 이용 및 안내 관련 (5개)
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] Foodding 서비스 정식 오픈 안내', '안녕하세요, Foodding입니다. 오랜 준비 끝에 서비스를 정식 오픈하게 되었습니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 개인정보 처리방침 개정 안내 (2025/12)', '개인정보 보호법 개정에 따라 처리방침이 변경될 예정입니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[안내] 시스템 정기 점검으로 인한 서비스 일시 중단 안내', '더 나은 서비스를 위해 새벽 2시부터 4시까지 점검이 진행됩니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[안내] 고객센터 운영 시간 변경 안내', '동절기 고객센터 운영 시간이 오전 10시부터로 변경됩니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 신규 결제 수단(Apple Pay) 도입 안내', '이제 Foodding에서도 간편하게 Apple Pay를 이용하실 수 있습니다.', SYSDATE, 0, 'N');

-- 2. 배송 및 품질 관련 (5개)
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[배송] 연말 택배 물량 증가로 인한 배송 지연 안내', '택배사 사정으로 인해 평소보다 1~2일 더 소요될 수 있습니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[품질] 신선식품 보관 및 섭취 가이드 안내', '펀딩하신 밀키트 상품의 신선도를 유지하는 최적의 방법입니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[배송] 제주 및 도서산간 지역 배송비 정책 변경 안내', '2026년부터 적용되는 추가 배송비 안내입니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 친환경 패키지(에코 박스) 도입 순차 적용 안내', '환경을 위해 테이프 없는 박스를 사용하기 시작합니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[배송] 1월 신년 연휴 배송 일정 공지', '신년 연휴 기간 동안의 배송 휴무 안내입니다.', SYSDATE, 0, 'N');

-- 3. 이벤트 및 혜택 관련 (5개)
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[이벤트] 친구 초대 시 5,000원 쿠폰 무제한 증정!', '함께 맛있는 펀딩을 즐겨보세요! 친구를 초대하면 혜택을 드립니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[당첨자발표] 리뷰왕 이벤트 당첨자 안내 (11월)', '참여해주신 모든 분들께 감사드립니다. 선정되신 10분을 공개합니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[혜택] 신규 회원 가입 축하 웰컴 패키지 안내', '가입만 해도 드리는 3종 쿠폰 혜택을 확인하세요.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[이벤트] 얼리버드 전용 무료 배송권 사용 안내', '슈퍼 얼리버드 고객님들을 위한 특별 혜택 안내입니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 멤버십 등급별 혜택 리뉴얼 안내', '더 풍성해진 등급별 적립 혜택을 소개합니다.', SYSDATE, 0, 'N');

-- 4. 커뮤니티 및 기타 (5개)
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 커뮤니티 클린 캠페인 안내', '타인에게 불쾌감을 주는 댓글은 제재 대상이 될 수 있습니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[안내] 펀딩금 반환 정책 변경 안내', '사용자 보호를 위해 펀딩금 반환 절차가 강화됩니다.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 푸딩(Foodding) 앱 2.0 업데이트 예고', '새로워진 디자인과 기능을 기대해 주세요!', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[안내] 메일 수신 동의 혜택 및 설정 방법', '혜택 정보를 놓치지 않으려면 수신 동의를 체크해 주세요.', SYSDATE, 0, 'N');

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CREATE_DATE, NOTICE_VIEW, NOTICE_YN)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '[공지] 연말 결산: 2025년 가장 사랑받은 푸드 프로젝트 TOP 10', '여러분이 만들어주신 놀라운 기록들입니다.', SYSDATE, 0, 'N');

COMMIT;