
INSERT INTO TB_USER (
    USER_NO, USER_ID, USER_PWD, USER_NAME,
    NICKNAME, BIRTH_DATE, GENDER, EMAIL,
    PHONE, ORIGIN_PROFILE, MODIFY_PROFILE,
    POSTCODE, MAIN_ADDRESS, DETAIL_ADDRESS,
    ENROLL_DATE, USER_YN, USER_ROLE
) VALUES (
    1, 'testUser', 'password', '테스트유저',
    'tester', SYSDATE, 'M', 'test@example.com',
    '010-0000-0000', NULL, NULL,
    '00000', '서울시', '어딘가 101',
    SYSDATE, 'Y', 'USER'
);