DROP TABLE TB_OPTION;
DROP TABLE TEMP_OPTION;

DROP SEQUENCE SEQ_OPTION_NO;
DROP SEQUENCE SEQ_TEMP_OPTION_NO;

CREATE SEQUENCE SEQ_OPTION_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_TEMP_OPTION_NO
START WITH 1
INCREMENT BY 1
NOCACHE;


-- 옵션 테이블
CREATE TABLE TB_OPTION (
    OPTION_NO NUMBER CONSTRAINT OPT_PK PRIMARY KEY,
    OPTION_NAME VARCHAR2(100) CONSTRAINT OPT_ONAME_NN NOT NULL,
    OPTION_CONTENT VARCHAR2(1000) CONSTRAINT OPT_CONTENT_NN NOT NULL,
    OPTION_PRICE NUMBER CONSTRAINT OPT_PRICE_NN NOT NULL,
    PRODUCT_NO NUMBER CONSTRAINT OPT_PNO_NN NOT NULL,
    CONSTRAINT OPT_PNO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)
);

-- 옵션 임시저장 테이블
CREATE TABLE TEMP_OPTION (
    OPTION_NO NUMBER CONSTRAINT TEMP_OP_PK PRIMARY KEY,
    OPTION_NAME VARCHAR2(100) ,
    OPTION_CONTENT VARCHAR2(1000),
    OPTION_PRICE NUMBER,
    TEMP_NO NUMBER
);

---------------------------------------------------------------------
COMMENT ON TABLE TB_OPTION IS '프로젝트 제품 옵션 테이블';

COMMENT ON COLUMN TB_OPTION.OPTION_NO IS '옵션 번호';
COMMENT ON COLUMN TB_OPTION.OPTION_NAME IS '옵션명';
COMMENT ON COLUMN TB_OPTION.OPTION_CONTENT IS '옵션 내용';
COMMENT ON COLUMN TB_OPTION.OPTION_PRICE IS '옵션 가격';
COMMENT ON COLUMN TB_OPTION.PRODUCT_NO IS '제품 번호(FK)';

---------------------------------------------------------------------
COMMENT ON TABLE TEMP_OPTION IS '임시저장 제품 옵션 테이블';

COMMENT ON COLUMN TEMP_OPTION.OPTION_NO IS '임시 옵션 번호';
COMMENT ON COLUMN TEMP_OPTION.OPTION_NAME IS '임시 옵션명';
COMMENT ON COLUMN TEMP_OPTION.OPTION_CONTENT IS '임시 옵션 내용';
COMMENT ON COLUMN TEMP_OPTION.OPTION_PRICE IS '임시 옵션 가격';
COMMENT ON COLUMN TEMP_OPTION.PRODUCT_NO IS '임시 제품 번호(FK)';