-- 검색 로그 테이블 및 시퀀스 추가 (기존 스키마에 적용할 DDL)

-- 테이블이 없다면 생성
CREATE TABLE SEARCH_LOG (
    LOG_ID NUMBER CONSTRAINT SLOG_PK PRIMARY KEY,
    KEYWORD VARCHAR2(100) CONSTRAINT SLOG_KEYWORD_NN NOT NULL,
    SEARCHED_AT DATE DEFAULT SYSDATE CONSTRAINT SLOG_DATE_NN NOT NULL
);

COMMENT ON TABLE SEARCH_LOG IS '검색어 기록 테이블';
COMMENT ON COLUMN SEARCH_LOG.LOG_ID IS '검색 로그 번호(PK)';
COMMENT ON COLUMN SEARCH_LOG.KEYWORD IS '검색어(소문자 저장)';
COMMENT ON COLUMN SEARCH_LOG.SEARCHED_AT IS '검색 시각';

-- 시퀀스가 없다면 생성
CREATE SEQUENCE SEQ_SEARCH_LOG_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 기존 DB에 DROP 문이 필요하다면 아래를 참고하세요.
-- DROP TABLE SEARCH_LOG;
-- DROP SEQUENCE SEQ_SEARCH_LOG_ID;
