DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE TEMPORARY CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_TEMP_NO;

CREATE SEQUENCE SEQ_PRODUCT_NO

START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_TEMP_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 제품 테이블

-- NOT NULL
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER CONSTRAINT PRO_PK PRIMARY KEY,
    PRODUCT_TITLE VARCHAR2(100) CONSTRAINT PRO_TI_NN NOT NULL,
    PRODUCT_DESC VARCHAR2(2000) CONSTRAINT PRO_DES_NN NOT NULL,
    STORY_HTML CLOB,
    STORY_JSON CLOB,
    TARGET_AMOUNT NUMBER CONSTRAINT PRO_TAMOUNT_NN NOT NULL,
    CURRENT_AMOUNT NUMBER CONSTRAINT PRO_CAMOUNT_NN NOT NULL,
    FUND_START_DATE DATE CONSTRAINT PRO_FSDATE_NN NOT NULL,
    FUND_END_DATE DATE CONSTRAINT PRO_FEDATE_NN NOT NULL,
     SHIP_START_DATE DATE CONSTRAINT PRO_SDATE_NN NOT NULL,
    PRODUCT_STATUS VARCHAR2(7) DEFAULT 'OPEN'
        CONSTRAINT PRO_STATUS_CHK CHECK (PRODUCT_STATUS IN ('OPEN','CLOSE','SUCCESS','FAIL'))
        CONSTRAINT PRO_STATUS_NN NOT NULL,
    CATEGORY VARCHAR2(30) CONSTRAINT PRO_CATE_NN NOT NULL,
    ORIGIN_THUMBNAIL VARCHAR2(100) CONSTRAINT PRO_OTHUMB_NN NOT NULL,
    MODIFY_THUMBNAIL VARCHAR2(100),
    REJECT_REASON VARCHAR2(1000),
    CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT PRO_CDATE_NN NOT NULL,
    PRODUCT_YN VARCHAR2(1) DEFAULT 'N',
    SELLER_NO NUMBER CONSTRAINT PRO_SNO_NN NOT NULL,
    CONSTRAINT PRO_SNO_FK FOREIGN KEY (SELLER_NO)
        REFERENCES SELLER_PROFILE(SELLER_NO)
);




-- 임시저장 테이블
CREATE TABLE TEMPORARY (
    TEMP_NO NUMBER CONSTRAINT TEMP_PK PRIMARY KEY,
    TEMP_TITLE VARCHAR2(100),
    TEMP_DESC VARCHAR2(2000),
    TARGET_AMOUNT NUMBER,
    FUND_START_DATE DATE,
    FUND_END_DATE DATE,
    CATEGORY VARCHAR2(30),
    ORIGIN_THUMBNAIL VARCHAR2(100),
    TEMP_STORY_HTML CLOB,
    TEMP_STORY_JSON CLOB,
    SHIP_START_DATE DATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    SELLER_NO NUMBER,
    CONSTRAINT TEMP_SNO_FK FOREIGN KEY (SELLER_NO)
        REFERENCES SELLER_PROFILE(SELLER_NO),
    TEMP_STATUS VARCHAR2(1) DEFAULT 'Y'
);


COMMENT ON TABLE PRODUCT IS '제품(푸슐랭) 정보 테이블';

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '제품 번호(PK)';
COMMENT ON COLUMN PRODUCT.PRODUCT_TITLE IS '제품 제목';
COMMENT ON COLUMN PRODUCT.PRODUCT_DESC IS '제품 상세 설명';
COMMENT ON COLUMN PRODUCT.STORY_HTML IS '프로젝트 스토리 HTML';
COMMENT ON COLUMN PRODUCT.STORY_JSON IS '프로젝트 스토리 JSON';
COMMENT ON COLUMN PRODUCT.TARGET_AMOUNT IS '목표 금액';
COMMENT ON COLUMN PRODUCT.CURRENT_AMOUNT IS '현재 후원 금액';
COMMENT ON COLUMN PRODUCT.FUND_START_DATE IS '펀딩 시작일';
COMMENT ON COLUMN PRODUCT.FUND_END_DATE IS '펀딩 종료일';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '상품 상태(OPEN/CLOSE/SUCCESS/FAIL)';
COMMENT ON COLUMN PRODUCT.CATEGORY IS '카테고리';
COMMENT ON COLUMN PRODUCT.ORIGIN_THUMBNAIL IS '썸네일 파일명';
COMMENT ON COLUMN PRODUCT.MODIFY_THUMBNAIL IS '수정할 썸네일 파일명';
COMMENT ON COLUMN PRODUCT.REJECT_REASON IS '관리자 반려 사유';
COMMENT ON COLUMN PRODUCT.CREATE_DATE IS '등록일';
COMMENT ON COLUMN PRODUCT.PRODUCT_YN IS '프로젝트 승인 여부(Y/N)';
COMMENT ON COLUMN PRODUCT.SELLER_NO IS '판매자 회원 번호(FK)';

---------------------------------------------------------------------
COMMENT ON TABLE TEMPORARY IS '임시 저장 테이블';

COMMENT ON COLUMN TEMPORARY.TEMP_NO IS '임시 저장 번호(PK)';
COMMENT ON COLUMN TEMPORARY.TEMP_TITLE IS '임시 제품 제목';
COMMENT ON COLUMN TEMPORARY.TEMP_DESC IS '임시 제품 설명';
COMMENT ON COLUMN TEMPORARY.TARGET_AMOUNT IS '임시 목표 금액';
COMMENT ON COLUMN TEMPORARY.FUND_START_DATE IS '임시 펀딩 시작일';
COMMENT ON COLUMN TEMPORARY.FUND_END_DATE IS '임시 펀딩 종료일';
COMMENT ON COLUMN TEMPORARY.CATEGORY IS '임시 카테고리';
COMMENT ON COLUMN TEMPORARY.ORIGIN_THUMBNAIL IS '썸네일 원본파일명';
COMMENT ON COLUMN TEMPORARY.TEMP_STORY_HTML IS '임시 저장 스토리 HTML';
COMMENT ON COLUMN TEMPORARY.TEMP_STORY_JSON IS '임시 저장 스토리 JSON';
COMMENT ON COLUMN TEMPORARY.SHIP_START_DATE IS '임시 배송시작일';
COMMENT ON COLUMN TEMPORARY.UPDATE_DATE IS '임시 저장 수정일';
COMMENT ON COLUMN TEMPORARY.SELLER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN TEMPORARY.TEMP_STATUS IS '공개 유무';

COMMIT;
