DROP TABLE SELLER_APPLICATION;

DROP SEQUENCE SEQ_SELLER_APP_NO

CREATE SEQUENCE SEQ_SELLER_APP_NO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

  CREATE TABLE SELLER_APPLICATION (
      APPLICATION_NO NUMBER CONSTRAINT SEL_APP_PK PRIMARY KEY,
      USER_NO NUMBER NOT NULL,
      APPLICANT_NAME VARCHAR2(100) NOT NULL,
      APPLICANT_EMAIL VARCHAR2(200) NOT NULL,
      APPLICANT_PHONE VARCHAR2(30) NOT NULL,
      BUSINESS_NAME VARCHAR2(200) NOT NULL,
      BUSINESS_NUMBER VARCHAR2(50),
      WEBSITE VARCHAR2(300),
      BRAND_DESCRIPTION VARCHAR2(2000),
      DOCUMENT_PATH VARCHAR2(500),
      STATUS VARCHAR2(10) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')) NOT NULL,
      ADMIN_MEMO VARCHAR2(1000),
      CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
      UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT SEL_APP_UNO_FK FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO)
  );
  
commit;